### ISSUE TITLE
http-digest crashes on missing opaque field from server

### ISSUE THREAD

**Issue by hleuwer** [catwell/lua-http-digest#6]
The opaque field in a servers authentication header is optional. Not respecting this leads to assertion of an error if no opaaue field is received (a) and to an error when constructing the send header with an an empty (nil) opaque content (b). 
Hence http-digest should
a) not assert an error when the opaque field is missing
b) either return the previously received opaque content (if received) or nothing (if not received).

[patch.txt](https://github.com/catwell/lua-http-digest/files/1485817/patch.txt)

**Comment by catwell** [comment]
Thank you, this is fixed in version 1.2.2 that I just released.

By any chance do you know a server that does not send that header, so I can try to add it to the tests?

**Comment by hleuwer** [comment]
I detected the problem by reading out AVM FritzBox home routers using soap in conjunction with http-digest. I do not know a public server though.

**Comment by catwell** [comment]
OK, thanks for the report anyway.
