### ISSUE TITLE
Variable names

### ISSUE THREAD

**Issue by erwan200026** [catwell/lua-http-digest#7]
Please change the name of the variables, I can't guess what's the meaning of "x", "T", "b", "c", etc...

**Comment by catwell** [comment]
Yeah, that is old code and some abbreviations are a bit too much, especially in the tests.

`b`, `c` and `h` are typical in LuaSocket-related code, they are the same variable names as 
in [the LuaSocket documentation](http://w3.impa.br/~diego/software/luasocket/http.html#request). I think they mean body, (return) code and headers.

I think I only use`T` to refer to the tests object. Not going to change that either, it's like `M`
for a module. You're dealing with that one important thing in the whole file, it should have a short name.

I did rename a few variables and add comments. If you need to understand something and don't, please ask.
